apiVersion: v1
kind: Service
metadata:
  name: adminapp-service
  namespace: cinematicket
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
  selector:
    app: adminapp