apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminapp
  namespace: cinematicket  # Same namespace, different app
spec:
  replicas: 1  # Number of replicas
  selector:
    matchLabels:
      app: adminapp  # Different app label
  template:
    metadata:
      labels:
        app: adminapp
    spec:
      containers:
      - name: adminapp
        image: leoncana10/cinemaadmin:latest  # Use your updated Docker image
        ports:
        - containerPort: 3001